# Enable the build cache to save time by reusing outputs produced by other successful builds.
# https://docs.gradle.org/current/userguide/build_cache.html
org.gradle.caching=true

# Enable the configuration cache to reuse the build configuration and enable parallel task execution.
# (Note that some plugins may not yet be compatible with the configuration cache.)
# https://docs.gradle.org/current/userguide/configuration_cache.html
# Disabled as of April 11th, 2026 due to https://github.com/FabricMC/fabric-loom/issues/1349, however it should run
# through GitHub Actions just fine
org.gradle.configuration-cache=false

# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Mod Properties
mod_version=0.1.0

# Dependencies are handled in ./gradle/libs.versions.toml